### ISSUE TITLE
Are you planning on implementing the following additional features?

### ISSUE THREAD

**Issue by sebykrueger** [manusa/helm-java#49]
- helm list
- helm upgrade --install

These would be very useful to have available in the library. Currently it feels a bit incomplete.

**Comment by manusa** [comment]
Yes, I am.

Next up are `helm repo` commands.

> These would be very useful to have available in the library. Currently it feels a bit incomplete.

Note that this started as a weekend stint that turned out quite fine. But it's still in a very early stage.
I'll be adding features little by little. Now that I know you're interested on these I'll prioritize.

If you're already using the library or are planning to do so in a production project, let me know. It might be interesting to add a section in the readme with success stories.

**Comment by manusa** [comment]
Hi folks,

I just released [v0.0.4](https://github.com/manusa/helm-java/releases/tag/v0.0.4) which includes both the features requested in this issue.

It'd be great to have your feedback. It would also help if you could share how are you planning to use this project and what are other possible use-cases you might be interested in or would like to explore.
